from uuid import uuid4
import csv

toy_names = [
    "Buzzy Bee Building Blocks",
    "Whirlwind Racing Cars",
    "Dizzy Dinosaur Puzzle",
    "Rainbow Sparkle Unicorn Doll",
    "Magnetic Alphabet Tiles",
    "Space Explorer Playset",
    "Fluttering Fairy Wings",
    "Giggling Gizmo Robot",
    "Tiny Tots Tea Party Set",
    "Jungle Safari Plush Animals",
    "Magic Castle Building Kit",
    "Doodle Art Drawing Board",
    "Penguin Pal Bowling Game",
    "Pixel Power Action Figures",
    "Enchanted Garden Playhouse",
    "Zooming Rocket Launcher",
    "Cuddly Kitty Stuffed Animal",
    "Ocean Adventure Bath Toys",
    "Puzzle Planet 3D Puzzle",
    "Monster Mash-Up Playdough",
    "Laser Tag Battle Blasters",
    "Mini Chef Cooking Playset",
    "Whistle and Wobble Yo-Yo",
    "Daring Dino Dig Excavation Kit",
    "Rainbow Ribbon Jump Rope",
    "Silly Sock Monkey Plush",
    "Mega Marble Maze Madness",
    "Jigsaw Jungle Puzzle",
    "Rock 'n' Roll Guitar Toy",
    "Fluffy Friends Pillow Pal",
    "Squiggly Squishy Stress Ball",
    "Robo-Buddy Remote Control Robot",
    "Colorful Kaleidoscope Viewer",
    "Dazzling Disco Dance Mat",
    "Snuggle Snail Plush Pillow",
    "Super Soaker Splash Gun",
    "Bouncing Bunny Hopscotch",
    "Musical Magic Keyboard",
    "Blastoff Bubble Blower",
    "Panda Pals Building Blocks",
    "Whacky Watercolor Art Set",
    "Slinky Spring Toy",
    "Jittery Jigsaw Puzzle",
    "Bouncing Ball Bonanza",
    "Mini Masterpiece Easel",
    "Dino Roar Sound Book",
    "Galactic Glow Stars",
    "Funky Fruit Jumping Rope",
    "Rolling Rainbow Skateboard",
    "Lego Land Adventure Set",
    "Safari Explorer Binoculars",
    "Scented Sticker Scrapbook",
    "Starry Night Light Projector",
    "Puzzlemania Board Game",
    "Daring Detective Spy Kit",
    "Twirling Tutu Ballerina Doll",
    "Rocket Racer Remote Car",
    "Teddy Bear Picnic Basket",
    "Glowing Galaxy Slime",
    "Funky Fashion Design Kit",
    "Jungle Jamboree Drum Set",
    "Lively Ladybug Kite",
    "Bubblegum Blast Bubble Wand",
    "Fishing Fun Magnetic Game",
    "Whiz Kid Science Lab",
    "Silly Snake Charmer Flute",
    "Woodland Wonderland Puppet Theater",
    "Tricky Tumbling Tumbleweed",
    "Gourmet Gummy Candy Maker",
    "Crazy Crocodile Water Slide",
    "Whistle While You Work Whistle",
    "Tumbling T-Rex Tumble Toy",
    "Lil' Picasso Art Smock",
    "Sailing Ship Adventure Set",
    "Moonwalk Moon Shoes",
    "Vibrant Velociraptor Puzzle",
    "Whisker Whirlwind Cat Toy",
    "Bubbly Bath Bubble Bath",
    "Blast-Off Balloon Rocket",
    "Wacky Watermelon Beach Ball",
    "Dizzy Doodle Drawing Pad",
    "Puzzle Palace Playhouse",
    "Squishy Squidgy Stress Toy",
    "Tickle Me Teddy Tickling Toy",
    "Flipping Fish Frisbee",
    "Glowing Ghostly Glow Sticks",
    "Stellar Stomp Rocket",
    "Candy Cane Cuddly Pillow",
    "Twisting Tornado Top",
    "Jungle Jumping Jacks",
    "Superhero Squad Action Figures",
    "Squeaky Clean Soapmaking Kit",
    "Zooming Zebra Zipline",
    "Dazzling Dragonfly Kite",
    "Flipping Fun Flipbook",
    "Splash and Slide Water Park",
    "Whimsical Wizard Wand",
    "Rock 'n' Roll Record Player",
    "Majestic Mermaid Tail Blanket",
    "Galactic Gumball Machine",
    "Safari Safari Binoculars",
    "Bubble Wrap Bonanza",
    "Twirling Tinkerbell Twirler",
    "Giggling Gopher Plush",
    "Neon Noodle Ninja Nunchucks",
    "Puzzle Perfection Board Game"
]

# Create a list of dictionaries with toy names and corresponding UUIDs
toys_data = [{'toy_id': str(uuid4()), 'toy_name': toy} for toy in toy_names]

# Specify the CSV file name
csv_file = 'toys.csv'

# Write the data to the CSV file
with open(csv_file, 'w', newline='') as file:
    fieldnames = ['toy_id', 'toy_name']
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # Write the header
    writer.writeheader()

    # Write the data
    writer.writerows(toys_data)
